# Python 3.12 tabanlı bir Docker imajı kullan
FROM python:3.12

# Çalışma dizinini ayarla
WORKDIR /app

# Gereksinimler dosyasını kopyala ve bağımlılıkları yükle
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Projenin geri kalanını kopyala
COPY . .

# Uygulamayı başlat
CMD ["waitress-serve", "--port=$PORT", "app:app"]